### ISSUE TITLE
testArithmeticalConvexhull enters an infinite loop  

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtal#997]
for some specific build configurations only.. 

see eg. https://github.com/DGtal-team/DGtal/pull/949

**Comment by isivigno** [comment]
May be related to the changes made in #950: @troussil could you have a look at it ?

**Comment by rolanddenis** [comment]
For my last PR, I've launch all the tests and they all passed, even the `testArithmeticalDSSConvexHull` but it was very long, 470s on my computer. It is maybe not an infinite loop ? 
In addition, only the travis builds that use `gcc` failed on this test, but when `clang` is used, it passed (this test).

I did some tests and here are the corresponding time for this test: 
- g++ (4.9.2), Debug: 470s,
- g++, Release: 29s,
- clang++ (3.5.0), Debug: 35s,
- clang++, Release: 27s.

There seems to be a huge slowdown of this test in debug mode with gcc...

**Comment by troussil** [comment]
Thank you @rolanddenis. You're right. 

`testArithmeticalDSSConvexHull` runs in 10 minutes on my computer.  @isivigno, you should remove the following line:
https://github.com/isivigno/DGtal/blob/cd73975c50b805ae9b53205c7548cceff4b9649a/tests/geometry/curves/testArithmeticalDSSConvexHull.cpp#L429 
because the added loop is too costly. 
Without it, the whole test runs in 10 seconds. 

PS. g++ (4.8.2), Debug

**Comment by dcoeurjo** [comment]
Seems to be solved.. closing
